template = "https://github.com/giellalt/template-lang-und"
rev_id = 291
template_sha = "4f5759693f3a379d63c31d91878cd6e3b56817ae"

[replacements]
__GLOTTOLOG_ID__ = "voti1245"
__REPO__ = "lang-vot-x-ext-kkankain"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
