template = "https://github.com/giellalt/template-lang-und"
rev_id = 314
template_sha = "ad51f89a72714ab21c4272c003b7692c820e2b18"

[replacements]
__GLOTTOLOG_ID__ = "voti1245"
__REPO__ = "lang-vot-x-ext-kkankain"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
