template = "https://github.com/giellalt/template-lang-und"
rev_id = 324
template_sha = "e348abe50c6a27ca569f7cb967cc9b3a3be7d9f9"

[replacements]
__GLOTTOLOG_ID__ = "voti1245"
__REPO__ = "lang-vot-x-ext-kkankain"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
